{
 "title": "SafeTunnels Cooja Dashboard",
 "description": "SafeTunnels Cooja Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensor1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ConnState",
   "type": "stat",
   "description": "Sensor Current Connection State",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT connState FROM SafeTunnelsCoojaDB.sensorsConnStateSeries WHERE sensorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ConnState Series",
   "type": "state-timeline",
   "description": "Sensor Connection State Time Series",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'20s'),\n  connState\nFROM sensorsConnStateSeries\nWHERE $__timeFilter(timestamp) AND sensorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "C02 Density",
   "type": "gauge",
   "description": "Sensor Current C02 Density",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT C02Density FROM SafeTunnelsCoojaDB.sensorsC02Series WHERE sensorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "C02 Density Series",
   "type": "timeseries",
   "description": "Sensor C02 Density Time Series",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  C02Density\nFROM sensorsC02Series\nWHERE $__timeFilter(timestamp) AND sensorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temp Series",
   "type": "timeseries",
   "description": "Sensor Temperature Time Series",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  temp\nFROM sensorsTempSeries\nWHERE $__timeFilter(timestamp) AND sensorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Sensor Current Temperature",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT temp FROM SafeTunnelsCoojaDB.sensorsTempSeries WHERE sensorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  { "title": "Sensor2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ConnState",
   "type": "stat",
   "description": "Sensor Current Connection State",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT connState FROM SafeTunnelsCoojaDB.sensorsConnStateSeries WHERE sensorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ConnState Series",
   "type": "state-timeline",
   "description": "Sensor Connection State Time Series",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  connState\nFROM sensorsConnStateSeries\nWHERE $__timeFilter(timestamp) AND sensorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "C02 Density",
   "type": "gauge",
   "description": "Sensor Current C02 Density",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT C02Density FROM SafeTunnelsCoojaDB.sensorsC02Series WHERE sensorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "C02 Density Series",
   "type": "timeseries",
   "description": "Sensor C02 Density Time Series",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  C02Density\nFROM sensorsC02Series\nWHERE $__timeFilter(timestamp) AND sensorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temp Series",
   "type": "timeseries",
   "description": "Sensor Temperature Time Series",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  temp\nFROM sensorsTempSeries\nWHERE $__timeFilter(timestamp) AND sensorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Sensor Current Temperature",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT temp FROM SafeTunnelsCoojaDB.sensorsTempSeries WHERE sensorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  { "title": "Actuator1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "ConnState",
   "type": "stat",
   "description": "Actuator Current Connection State",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT connState FROM SafeTunnelsCoojaDB.actuatorsConnStateSeries WHERE actuatorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ConnState Series",
   "type": "state-timeline",
   "description": "Actuator Connection State Time Series",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  connState\nFROM actuatorsConnStateSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fan Relative Speed",
   "type": "gauge",
   "description": "Actuator Current Fan Relative Speed",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT fanRelSpeed FROM SafeTunnelsCoojaDB.actuatorsFanSeries WHERE actuatorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Fan Relative Speed Series",
   "type": "timeseries",
   "description": "Actuator Fan Relative Speed Time Series",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  fanRelSpeed\nFROM actuatorsFanSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light State Series",
   "type": "state-timeline",
   "description": "Actuator Light State Time Series",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  lightState\nFROM actuatorsLightSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light State",
   "type": "stat",
   "description": "Actuator Current Light State",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT lightState FROM SafeTunnelsCoojaDB.actuatorsLightSeries WHERE actuatorID = 1 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  { "title": "Actuator2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "ConnState",
   "type": "stat",
   "description": "Actuator Current Connection State",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT connState FROM SafeTunnelsCoojaDB.actuatorsConnStateSeries WHERE actuatorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "ConnState Series",
   "type": "state-timeline",
   "description": "Actuator Connection State Time Series",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  connState\nFROM actuatorsConnStateSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fan Relative Speed",
   "type": "gauge",
   "description": "Actuator Current Fan Relative Speed",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT fanRelSpeed FROM SafeTunnelsCoojaDB.actuatorsFanSeries WHERE actuatorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Fan Relative Speed Series",
   "type": "timeseries",
   "description": "Actuator Fan Relative Speed Time Series",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  fanRelSpeed\nFROM actuatorsFanSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light State Series",
   "type": "state-timeline",
   "description": "Actuator Light State Time Series",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,'5s'),\n  lightState\nFROM actuatorsLightSeries\nWHERE $__timeFilter(timestamp) AND actuatorID = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light State",
   "type": "stat",
   "description": "Actuator Current Light State",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SafeTunnelsCoojaDB",
     "rawSql": "SELECT lightState FROM SafeTunnelsCoojaDB.actuatorsLightSeries WHERE actuatorID = 2 ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  }
 ]
}